apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-subscriber
  labels:
    app: python-subscriber
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-subscriber
  template:
    metadata:
      labels:
        app: python-subscriber
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "python"
        dapr.io/app-port: "5001"
    spec:
      containers:
      - name: python-subscriber
        image: jonaspkit/dapr-python:latest
        ports:
        - containerPort: 5001
        imagePullPolicy: Always
